parameters: 
  markocupic.contao_utf8_arrows_insert_tag.leftwards_arrow: 8592
  markocupic.contao_utf8_arrows_insert_tag.upwards_arrow: 8593
  markocupic.contao_utf8_arrows_insert_tag.rightwards_arrow: 8594
  markocupic.contao_utf8_arrows_insert_tag.downwards_arrow: 8595
  markocupic.contao_utf8_arrows_insert_tag.left_right_arrow: 8596
  markocupic.contao_utf8_arrows_insert_tag.up_down_arrow: 8597
  markocupic.contao_utf8_arrows_insert_tag.north_west_arrow: 8598
  markocupic.contao_utf8_arrows_insert_tag.north_east_arrow: 8599
  markocupic.contao_utf8_arrows_insert_tag.south_east_arrow: 8600
  markocupic.contao_utf8_arrows_insert_tag.south_west_arrow: 8601
  markocupic.contao_utf8_arrows_insert_tag.leftwards_arrow_with_stroke: 8602
  markocupic.contao_utf8_arrows_insert_tag.rightwards_arrow_with_stroke: 8603
  markocupic.contao_utf8_arrows_insert_tag.leftwards_wave_arrow: 8604
  markocupic.contao_utf8_arrows_insert_tag.rightwards_wave_arrow: 8605
  markocupic.contao_utf8_arrows_insert_tag.leftwards_two_headed_arrow: 8606
  markocupic.contao_utf8_arrows_insert_tag.upwards_two_headed_arrow: 8607
  markocupic.contao_utf8_arrows_insert_tag.rightwards_two_headed_arrow: 8608
  markocupic.contao_utf8_arrows_insert_tag.downwards_two_headed_arrow: 8609
  markocupic.contao_utf8_arrows_insert_tag.leftwards_arrow_with_tail: 8610
  markocupic.contao_utf8_arrows_insert_tag.rightwards_arrow_with_tail: 8611
  markocupic.contao_utf8_arrows_insert_tag.leftwards_arrow_from_bar: 8612
  markocupic.contao_utf8_arrows_insert_tag.upwards_arrow_from_bar: 8613
  markocupic.contao_utf8_arrows_insert_tag.rightwards_arrow_from_bar: 8614
  markocupic.contao_utf8_arrows_insert_tag.downwards_arrow_from_bar: 8615
  markocupic.contao_utf8_arrows_insert_tag.up_down_arrow_with_base: 8616
  markocupic.contao_utf8_arrows_insert_tag.leftwards_arrow_with_hook: 8617
  markocupic.contao_utf8_arrows_insert_tag.rightwards_arrow_with_hook: 8618
  markocupic.contao_utf8_arrows_insert_tag.leftwards_arrow_with_loop: 8619
  markocupic.contao_utf8_arrows_insert_tag.rightwards_arrow_with_loop: 8620
  markocupic.contao_utf8_arrows_insert_tag.left_right_wave_arrow: 8621
  markocupic.contao_utf8_arrows_insert_tag.left_right_arrow_with_stroke: 8622
  markocupic.contao_utf8_arrows_insert_tag.downwards_zigzag_arrow: 8623
  markocupic.contao_utf8_arrows_insert_tag.upwards_arrow_with_tip_leftwards: 8624
  markocupic.contao_utf8_arrows_insert_tag.upwards_arrow_with_tip_rightwards: 8625
  markocupic.contao_utf8_arrows_insert_tag.downwards_arrow_with_tip_leftwards: 8626
  markocupic.contao_utf8_arrows_insert_tag.downwards_arrow_with_tip_rightwards: 8627
  markocupic.contao_utf8_arrows_insert_tag.rightwards_arrow_with_corner_downwards: 8628
  markocupic.contao_utf8_arrows_insert_tag.downwards_arrow_with_corner_leftwards: 8629
  markocupic.contao_utf8_arrows_insert_tag.anticlockwise_top_semicircle_arrow: 8630
  markocupic.contao_utf8_arrows_insert_tag.clockwise_top_semicircle_arrow: 8631
  markocupic.contao_utf8_arrows_insert_tag.north_west_arrow_to_long_bar: 8632
  markocupic.contao_utf8_arrows_insert_tag.leftwards_arrow_to_bar_over_rightwards_arrow_to_bar: 8633
  markocupic.contao_utf8_arrows_insert_tag.anticlockwise_open_circle_arrow: 8634
  markocupic.contao_utf8_arrows_insert_tag.clockwise_open_circle_arrow: 8635
  markocupic.contao_utf8_arrows_insert_tag.leftwards_harpoon_with_barb_upwards: 8636
  markocupic.contao_utf8_arrows_insert_tag.leftwards_harpoon_with_barb_downwards: 8637
  markocupic.contao_utf8_arrows_insert_tag.upwards_harpoon_with_barb_rightwards: 8638
  markocupic.contao_utf8_arrows_insert_tag.upwards_harpoon_with_barb_leftwards: 8639
  markocupic.contao_utf8_arrows_insert_tag.rightwards_harpoon_with_barb_upwards: 8640
  markocupic.contao_utf8_arrows_insert_tag.rightwards_harpoon_with_barb_downwards: 8641
  markocupic.contao_utf8_arrows_insert_tag.downwards_harpoon_with_barb_rightwards: 8642
  markocupic.contao_utf8_arrows_insert_tag.downwards_harpoon_with_barb_leftwards: 8643
  markocupic.contao_utf8_arrows_insert_tag.rightwards_arrow_over_leftwards_arrow: 8644
  markocupic.contao_utf8_arrows_insert_tag.upwards_arrow_leftwards_of_downwards_arrow: 8645
  markocupic.contao_utf8_arrows_insert_tag.leftwards_arrow_over_rightwards_arrow: 8646
  markocupic.contao_utf8_arrows_insert_tag.leftwards_paired_arrows: 8647
  markocupic.contao_utf8_arrows_insert_tag.upwards_paired_arrows: 8648
  markocupic.contao_utf8_arrows_insert_tag.rightwards_paired_arrows: 8649
  markocupic.contao_utf8_arrows_insert_tag.downwards_paired_arrows: 8650
  markocupic.contao_utf8_arrows_insert_tag.leftwards_harpoon_over_rightwards_harpoon: 8651
  markocupic.contao_utf8_arrows_insert_tag.rightwards_harpoon_over_leftwards_harpoon: 8652
  markocupic.contao_utf8_arrows_insert_tag.leftwards_double_arrow_with_stroke: 8653
  markocupic.contao_utf8_arrows_insert_tag.left_right_double_arrow_with_stroke: 8654
  markocupic.contao_utf8_arrows_insert_tag.rightwards_double_arrow_with_stroke: 8655
  markocupic.contao_utf8_arrows_insert_tag.leftwards_double_arrow: 8656
  markocupic.contao_utf8_arrows_insert_tag.upwards_double_arrow: 8657
  markocupic.contao_utf8_arrows_insert_tag.rightwards_double_arrow: 8658
  markocupic.contao_utf8_arrows_insert_tag.downwards_double_arrow: 8659
  markocupic.contao_utf8_arrows_insert_tag.left_right_double_arrow: 8660
  markocupic.contao_utf8_arrows_insert_tag.up_down_double_arrow: 8661
  markocupic.contao_utf8_arrows_insert_tag.north_west_double_arrow: 8662
  markocupic.contao_utf8_arrows_insert_tag.north_east_double_arrow: 8663
  markocupic.contao_utf8_arrows_insert_tag.south_east_double_arrow: 8664
  markocupic.contao_utf8_arrows_insert_tag.south_west_double_arrow: 8665
  markocupic.contao_utf8_arrows_insert_tag.leftwards_triple_arrow: 8666
  markocupic.contao_utf8_arrows_insert_tag.rightwards_triple_arrow: 8667
  markocupic.contao_utf8_arrows_insert_tag.leftwards_squiggle_arrow: 8668
  markocupic.contao_utf8_arrows_insert_tag.rightwards_squiggle_arrow: 8669
  markocupic.contao_utf8_arrows_insert_tag.upwards_arrow_with_double_stroke: 8670
  markocupic.contao_utf8_arrows_insert_tag.downwards_arrow_with_double_stroke: 8671
  markocupic.contao_utf8_arrows_insert_tag.leftwards_dashed_arrow: 8672
  markocupic.contao_utf8_arrows_insert_tag.upwards_dashed_arrow: 8673
  markocupic.contao_utf8_arrows_insert_tag.rightwards_dashed_arrow: 8674
  markocupic.contao_utf8_arrows_insert_tag.downwards_dashed_arrow: 8675
  markocupic.contao_utf8_arrows_insert_tag.leftwards_arrow_to_bar: 8676
  markocupic.contao_utf8_arrows_insert_tag.rightwards_arrow_to_bar: 8677
  markocupic.contao_utf8_arrows_insert_tag.leftwards_white_arrow: 8678
  markocupic.contao_utf8_arrows_insert_tag.upwards_white_arrow: 8679
  markocupic.contao_utf8_arrows_insert_tag.rightwards_white_arrow: 8680
  markocupic.contao_utf8_arrows_insert_tag.downwards_white_arrow: 8681
  markocupic.contao_utf8_arrows_insert_tag.upwards_white_arrow_from_bar: 8682
  markocupic.contao_utf8_arrows_insert_tag.upwards_white_arrow_on_pedestal: 8683
  markocupic.contao_utf8_arrows_insert_tag.upwards_white_arrow_on_pedestal_with_horizontal_bar: 8684
  markocupic.contao_utf8_arrows_insert_tag.upwards_white_arrow_on_pedestal_with_vertical_bar: 8685
  markocupic.contao_utf8_arrows_insert_tag.upwards_white_double_arrow: 8686
  markocupic.contao_utf8_arrows_insert_tag.upwards_white_double_arrow_on_pedestal: 8687
  markocupic.contao_utf8_arrows_insert_tag.rightwards_white_arrow_from_wall: 8688
  markocupic.contao_utf8_arrows_insert_tag.north_west_arrow_to_corner: 8689
  markocupic.contao_utf8_arrows_insert_tag.south_east_arrow_to_corner: 8690
  markocupic.contao_utf8_arrows_insert_tag.up_down_white_arrow: 8691
  markocupic.contao_utf8_arrows_insert_tag.right_arrow_with_small_circle: 8692
  markocupic.contao_utf8_arrows_insert_tag.downwards_arrow_leftwards_of_upwards_arrow: 8693
  markocupic.contao_utf8_arrows_insert_tag.three_rightwards_arrows: 8694
  markocupic.contao_utf8_arrows_insert_tag.leftwards_arrow_with_vertical_stroke: 8695
  markocupic.contao_utf8_arrows_insert_tag.rightwards_arrow_with_vertical_stroke: 8696
  markocupic.contao_utf8_arrows_insert_tag.left_right_arrow_with_vertical_stroke: 8697
  markocupic.contao_utf8_arrows_insert_tag.leftwards_arrow_with_double_vertical_stroke: 8698
  markocupic.contao_utf8_arrows_insert_tag.rightwards_arrow_with_double_vertical_stroke: 8699
  markocupic.contao_utf8_arrows_insert_tag.left_right_arrow_with_double_vertical_stroke: 8700
  markocupic.contao_utf8_arrows_insert_tag.leftwards_open-headed_arrow: 8701
  markocupic.contao_utf8_arrows_insert_tag.rightwards_open-headed_arrow: 8702
  markocupic.contao_utf8_arrows_insert_tag.left_right_open-headed_arrow: 8703

